# Generated by Django 5.0.4 on 2024-04-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_crime_delete_mapitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=350)),
                ('startTime', models.CharField(max_length=350)),
                ('endTime', models.CharField(max_length=350)),
                ('when', models.CharField(max_length=350)),
                ('eventType', models.CharField(max_length=350)),
            ],
        ),
        migrations.DeleteModel(
            name='Crime',
        ),
    ]
