# Generated by Django 5.0.4 on 2024-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_mapevent_delete_crime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapevent',
            name='name',
            field=models.CharField(default='unnamed', max_length=350),
            preserve_default=False,
        ),
    ]
