# Generated by Django 5.0.4 on 2024-04-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0005_mapnews_delete_mapevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapnews',
            name='endTime',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='mapnews',
            name='startTime',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='mapnews',
            name='when',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
